[build]
builder = "dockerfile"

[deploy]
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
RAILS_ENV = "production"
NODE_ENV = "production"
INSTALLATION_ENV = "docker"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"
NUMBER_OF_PROXIES = "1"
